apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: jfupzg8go-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jfupzg8go-go 
  name: jfupzg8go-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: jfupzg8go-go 
